require(package "openbox");
SetTimestamp_Classify_FakeApp@_@set_timestamp::SetTimestamp();
Classify_FakeApp@_@counter::MultiCounter();
Classify_FakeApp@_@classifier::Classifier(14/05%0f 36/0016, -);
Guard_Classify_FakeApp@_@utilization_monitor::UtilizationMonitor(WINDOW 100, PROC_THRESHOLD 2.0);
FromDevice_FakeApp@_@from_device::FromDevice(eth0, SNIFFER true, PROMISC true);
FromDevice_FakeApp@_@mark_ip_header::AutoMarkIPHeader();
FromDevice_FakeApp@_@counter::Counter();
ToDump1_FakeApp@_@to_dump::ToDump(/home/mininet/hello1.pcap, UNBUFFERED true);
ToDump2_FakeApp@_@to_dump::ToDump(/home/mininet/hello2.pcap, UNBUFFERED true);
Classify_FakeApp@_@classifier[0]->[0]Classify_FakeApp@_@counter;
Classify_FakeApp@_@classifier[1]->[1]Classify_FakeApp@_@counter;
FromDevice_FakeApp@_@from_device[0]->[0]FromDevice_FakeApp@_@mark_ip_header;
FromDevice_FakeApp@_@mark_ip_header[0]->[0]FromDevice_FakeApp@_@counter;
SetTimestamp_Classify_FakeApp@_@set_timestamp[0]->[0]Classify_FakeApp@_@classifier;
Classify_FakeApp@_@counter[0]->[0]Guard_Classify_FakeApp@_@utilization_monitor;
Classify_FakeApp@_@counter[1]->[0]Guard_Classify_FakeApp@_@utilization_monitor;
FromDevice_FakeApp@_@counter[0]->[0]SetTimestamp_Classify_FakeApp@_@set_timestamp;
Guard_Classify_FakeApp@_@utilization_monitor[0]->[0]ToDump1_FakeApp@_@to_dump;
Guard_Classify_FakeApp@_@utilization_monitor[1]->[0]ToDump2_FakeApp@_@to_dump;
